openapi: '3.0.2'
info:
  title: Dummy API
  version: '1.0'
servers: # Not mandatory
  - url: https://external-system-3scale-apicast-staging.ocp4.work/
paths:
  /:
    get:
      responses:
        '200':
          description: OK

components:
  schemas:
    Data: 
      type: object 
      required: 
        - id
      properties:
        message: 
          type: string
        access:
          type: string